// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addChargePoint": {
            "post": {
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Priority",
                        "name": "Priority",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "GroupId",
                        "name": "GroupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/addChargePointConnector": {
            "post": {
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ChargePointId",
                        "name": "ChargePointId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Status",
                        "name": "Status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/addGroup": {
            "post": {
                "parameters": [
                    {
                        "type": "integer",
                        "description": "maxCurrent",
                        "name": "maxCurrent",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/changeChargePointPriority/:chargePointId/:priority": {
            "put": {
                "parameters": [
                    {
                        "type": "integer",
                        "description": "priority",
                        "name": "priority",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "chargePointId",
                        "name": "chargePointId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Priority is not a number",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/changeConnectorStatus/:connectorId/:status": {
            "put": {
                "parameters": [
                    {
                        "type": "integer",
                        "description": "status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "connectorId",
                        "name": "connectorId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Wrong status value",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Missing status value",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/changeMaxCurrentGroup/:groupId/:maxCurrent": {
            "put": {
                "parameters": [
                    {
                        "type": "integer",
                        "description": "maxCurrent",
                        "name": "maxCurrent",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "groupId",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "MaxCurrent must be greater or equal to 0",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GLCharge",
	Description:      "GLCharge API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
