basePath: /
definitions:
  handlers.ChangeChargePointPriorityReq:
    properties:
      ChargePointId:
        example: 1
        type: integer
      Priority:
        example: 1
        type: integer
    type: object
  handlers.ChangeConnectorStatusReq:
    properties:
      Id:
        example: 1
        type: integer
      Status:
        example: Available
        type: string
    type: object
  handlers.ChangeMaxCurrentGroupReq:
    properties:
      Id:
        example: 1
        type: integer
      MaxCurrent:
        example: 100
        type: number
    type: object
  handlers.ChargePointConnectorReq:
    properties:
      ChargePointId:
        example: 1
        type: integer
      Status:
        example: Available
        type: string
    type: object
  handlers.ChargePointReq:
    properties:
      GroupId:
        example: 1
        type: integer
      Priority:
        example: 1
        type: integer
    type: object
  handlers.GroupReq:
    properties:
      MaxCurrent:
        example: 100
        type: number
    type: object
  handlers.HandlerRes:
    properties:
      resultMap:
        additionalProperties:
          type: number
        type: object
    type: object
host: localhost:8080
info:
  contact: {}
  description: GLCharge API documentation.
  title: GLCharge
  version: "1.0"
paths:
  /addChargePoint:
    post:
      parameters:
      - description: ChargePointReq
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ChargePointReq'
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
  /addChargePointConnector:
    post:
      parameters:
      - description: ChargePointConnectorReq
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ChargePointConnectorReq'
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
  /addGroup:
    post:
      parameters:
      - description: GroupReq
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.GroupReq'
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
  /changeChargePointPriority:
    put:
      consumes:
      - application/json
      parameters:
      - description: ChangeChargePointPriorityReq
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ChangeChargePointPriorityReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HandlerRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /changeConnectorStatus:
    put:
      consumes:
      - application/json
      parameters:
      - description: ChangeConnectorStatusReq
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ChangeConnectorStatusReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HandlerRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /changeMaxCurrentGroup:
    put:
      consumes:
      - application/json
      parameters:
      - description: ChangeMaxCurrentGroupReq
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ChangeMaxCurrentGroupReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HandlerRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
swagger: "2.0"
