services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: glcharge
  go:
    build: 
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - CONN_STR=postgresql://root:root@postgres:5432/glcharge?sslmode=disable